### PR TITLE
kcqrs/eventstore: read all events from the event store

### PR DESCRIPTION
**Pull request by mgenov**
Added API for retrieving of all events from the event store. The GAE implementation of the EventStore uses an additional Entity to keep an index of all added events and is used for querying of the datastore.

The kcqrs-client is updated regarding this change and calls remote HTTP endpoint for retrieving of the events.

image

### CODE REVIEW

**Comment by mlesikov** [comment]
what is the source scenario for this change -  recover a view, that is build from multiple aggregates?

**Comment by mgenov** [comment]
The View code to be independent from the async message bus and to provide a clean way for synchronization with the eventstore.

**Comment by mgenov** [comment]
Friendly Reminder.

**Comment by mlesikov** [comment]
@mgenov  I'm not sure, how get all will to the job, but I'm ok.

**Review by mlesikov — APPROVED** [review]

**Pull request merged**
